stages:
  - release-npm
  - release-github

release-npm:
  stage: release-npm
  script:
    - echo publish to npm
    - npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
    - npm profile get
  #  - npm publish
  only:
    - web # only autorun when click “RunPipeLine” on GitLab WebSite
  when: 
      manual
  allow_failure: false

release-github:
  stage: release-github
  script:
    - echo push to github
  only:
    - web # only autorun when click “RunPipeLine” on GitLab WebSite
  when: 
      manual
  allow_failure: false