image: node:17.6.0
stages:
  - release-npm
  - release-github

release-npm:
  stage: release-npm
  artifacts:
    paths:
      - dist/
      - coverage
      - doc
  script:
    - node -v
    - npm -v
    - npm install
    - npm run test
    - npm run build
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}">.npmrc
    - ls -a
    - cat .npmrc
    - npm publish --verbose
    - rm -f .npmrc
  only:
    - web # only autorun when click “RunPipeLine” on GitLab WebSite
  when: 
      manual
  allow_failure: false

release-github:
  stage: release-github
  script:
    - git config --global user.email "wrench_pipeline@sensors.com"
    - git config --global user.name "wrench_pipeline"
    - git branch
    - git checkout master
    - git pull
    - git branch
    - git add .
    - git commit -m "update dist" || echo "No changes to commit"
    - git push  http://gitlab-ci-token:${GITLAB_TOKEN}@gitlab.sensorsdata.cn/team/rd/jssdk/wrench.git master
    - git fetch --unshallow origin
    - git push -f https://${GITHUB_TOKEN}@github.com/sensorsdata/wrench.git master
    # release documents
    - cp -r doc ../
    - cd ..
    - ls
    - cd ./doc
    - ls
    - git init
    - git checkout -b main
    - git add .
    - git commit -m "update docs"
    - git push -f https://${DOC_TOKEN}@github.com/LuLu0110/LuLu0110.github.io.git main
  only:
    - web # only autorun when click “RunPipeLine” on GitLab WebSite
  when: 
      manual
  allow_failure: false